### ISSUE TITLE
Model initialization

### ISSUE THREAD

**Issue by weleslie** [YingqianWang/LF-InterNet#1]
Hello, thanks for sharing. I notice that the model is initialized using Xavier method in your paper, but I don't find correspoding code in this repo. So I'm confused and want to know why, thanks a lot! From a pytorch beginner.

**Comment by YingqianWang** [comment]
Thanks for your attention. We have checked our training codes and found that we had removed the initialization part by mistake during cleaning the codes. We have updated 'train.py' and added the corresponding parts. Kindly note that, 1) all pretrained models available in this repo were trained using the Xavier initialization method, which is consistent with our paper; 2) we have also tried other initialization methods and didn't found significant difference in performance.

**Comment by weleslie** [comment]
Your answer is useful to me, thank you so much!
