### ISSUE TITLE
Question for Dataset

### ISSUE THREAD

**Issue by NagatoYukisan** [YingqianWang/LF-InterNet#11]
Thanks for your sharing. I found that the images in your dataset are brighter and more comfortable than the dataset downloaded directly from the official website. How do you handle the original images, can you share the code?

**Comment by YingqianWang** [comment]
Thanks for your attention. At the very beginning, I noticed that images in the HCInew datasets are of low contrast. Then, I mannually adjusted their contrasts using a the Microsoft Piture Manager software for better visualization. I'm sorry that I did not save the parameters for this adjustment. I suggest to use our released datasets for training and evaluation (especially evaluation).
