### ISSUE TITLE
Training details about Datasets

### ISSUE THREAD

**Issue by leftdoor** [YingqianWang/LF-InterNet#5]
Thanks for sharing. When I see the codes, I can't find random ﬂipping and 90-degree rotation in data perprocessing. And I trained the project(5×5 and upscale=4,channels=64) by myself, but my results on the test datasets  are a little lower than yours(PSNR on six dataset: 29.45,30.99,37.17,31.62,30.39,31.78), but your pretrained model can get the result in this paper, so i think maybe is the problem about data augmentation(you did it but i didn't)?

**Comment by YingqianWang** [comment]
Thanks for the comments. The codes for data augmentation are at Line 33-43 of 'utils.py'. Your reproduced results are very close to our released ones. We thind that the degradation may be caused by randomness during training.

**Comment by YingqianWang** [comment]
You can try to increase the HR patchsize to 128 when generate training data for 4xSR. This may help to improve the SR performance. The size of LR patches for 2xSR and 4xSR should be kept identical (i.e., 32x32).

**Comment by leftdoor** [comment]
Thanks for your reply, and i will try it.
