### ISSUE TITLE
Why L is set to 2 for calculating SSIM

### ISSUE THREAD

**Issue by backkon** [YingqianWang/LF-InterNet#6]
Hello, your work is excellent! But I have some questions, I would like to ask why L is set to 2 in the Matlab code for calculating SSIM, and should not be 1?

**Comment by YingqianWang** [comment]
Sorry for the late reply. We just followed the previous works to calculate the SSIM values. There are several versions of the SSIM evaluation pipeline. The calculation pipeline of SSIM should be consistent among different methods.
